### ISSUE TITLE
Issues with core_base_statistical_areas in clean-data.Rmd

### ISSUE THREAD

**Issue by jrdusendang** [phispu/app-cpi-eda#3]
When I run line 28 

cbsa_sf_prelim <- core_based_statistical_areas()

I get the following error 

Retrieving data for the year 2022
Warning in unzip(file_loc, exdir = tmp) :
  error 1 in extracting from zip file
Error: Cannot open "C:\Users\jduse\AppData\Local\Temp\RtmpozSCzt"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.

So looks like we may have to have something downloaded into the repo

**Comment by phispu** [comment]
Fixed-- file saved in data folder now!
